name: date_utils
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Eric Windmill <ericwindmill@gmail.com>
description: A Dart library for manipulating DateTimes.
version: 0.2.0
homepage: https://github.com/apptreesoftware/date_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.19.0

dev_dependencies:
  test: ^1.16.5
